### ISSUE TITLE
Stress-testing Type: Okta.com + Help Center

### ISSUE THREAD

**Issue by edburyenegren-okta** [okta/odyssey#156]

**Comment by nickarcidy-okta** [comment]
https://www.figma.com/file/zh63JhskjOJ4l2R8qjPy4S/Type-Stress-Test-web?node-id=0%3A1

See above for my stress test of Okta.com and Help Center. 

I'm concluding that the proposed type scale adjustments will not impact Okta.com or Help Center in any significant way. Newer areas of .com such as the homepage and Help Center (WIP) are currently using something close to the proposed scale already, so the jump isn't a big one. For the older .com pages that use a type scale from the brand bible days before my time, there are enough sizes in the proposed scale that are close enough to what currently exists so as not to cause a major disruption. These pages will be entirely re-designed in the near future anyway. 

The biggest area of change is in the homepage hero, with the new guidelines around subheads. I feel as though the new subhead size looks quite large in that context, and that we should consider recommending subheads be _at least_ two sizes down from the heading size, rather than _precisely_ two sizes down. Sometimes, an H1 + body does the trick.

**Comment by edburyenegren-okta** [comment]
Thanks, @nickarcidy-okta! Super helpful to see this and know you're feeling good about the scale. It's also good to see that, while the UI scales up, it's not as drastic a change as folks might fear. A few new orphans here and there, but those shouldn't be large hurdles.
