### ISSUE TITLE
Restyle Courage Form

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#222]
- [x] Form (header, titles, etc)
- [x] Text Input
- [x] Select
- [x] Radio
- [x] Checkbox
- [x] Errors
- [x] Input + Label/Button

**Comment by edburyenegren-okta** [comment]
<img width="553" alt="Screenshot 2019-11-06 15 47 08" src="https://user-images.githubusercontent.com/36284167/68348733-9c503380-00af-11ea-96ba-a54d4ff91c96.png">

Will need a solution for us since our button borders are 2px and inputs are 1px

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta what do we want the active state for these dropdowns to look like?

I figure blue border all around like inputs. Maybe not the blue horizontal divider tho - feels loud?

`:hover` color on items should prolly be action, light or a gray?

<img width="442" alt="Screenshot 2019-11-06 16 21 07" src="https://user-images.githubusercontent.com/36284167/68349275-7af04700-00b1-11ea-8e7d-3e216bab0829.png">

<img width="432" alt="Screenshot 2019-11-06 16 21 13" src="https://user-images.githubusercontent.com/36284167/68349282-817ebe80-00b1-11ea-81a6-bea1f435ef92.png">

**Comment by edburyenegren-okta** [comment]
<img width="406" alt="Screenshot 2019-11-06 16 58 40" src="https://user-images.githubusercontent.com/36284167/68350912-be00e900-00b6-11ea-87f8-8435f0a7e8f3.png">

Spacing is a little... generous here. Since we can't change the HTML structure, it's been a bear getting everything to line up, so our radios and checkboxes have the same padding on them as inputs for now.

**Comment by edburyenegren-okta** [comment]
@johnintrater-okta i've started inventorying the components that are coming up in this ticket to better track all the work

**Comment by edburyenegren-okta** [comment]
merged in https://github.com/okta/okta-ui/pull/1733
