### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#351]

**Comment by alexdahl-okta** [comment]
+1 from dev docs.

We have a couple instances of cards today, and I think we are internally inconsistent. We would love to wholesale adopt Odyssey cards and remove all our CSS for them.

**Comment by jacobpuckett-okta** [comment]
Here are two instances where we'd like a card

# Customizations section

This is a reorganization of primarily UI customizations that are currently strewn through the Admin Console. Ideally we could use a card for this page to *show* the users what they're looking for, rather than just tell them. Our current plan is the use a table.

![image](https://user-images.githubusercontent.com/48925519/78581300-b2e6ec00-7801-11ea-8714-50a4acf8603f.png)

# Recent Sign-ins

This is part of the End User Dashboard. We organize users' recent sign-ins by device. We are currently using a table, but cards would be ideal. Clicking triggers are drawer to show all sign-ins for that device. 

![image](https://user-images.githubusercontent.com/48925519/78581467-eaee2f00-7801-11ea-90bd-e2417d253412.png)
