### ISSUE TITLE
Icons: Inventory & Research

### ISSUE THREAD

**Issue by johnintrater-okta** [okta/odyssey#372]
- [x] Reach out to Brand/Nick regarding scope of this work
- [x] Take inventory of existing icons in product
- [x] Identify problem areas and synthesize findings
- [x] Create standards for svg output

**Comment by johnintrater-okta** [comment]
@joejezowski-okta @nickarcidy-okta @edburyenegren-okta @arnoldsandoval-okta who is owning this ticket for this sprint?

**Comment by nickarcidy-okta** [comment]
Just as a heads up - were working with another agency solely on icons (system through larger marketing-level) right now. Syncing with Joe on this early next week. Will cover off with him on how we can enable you all to not be blocked in the meantime with near-term needs

**Comment by joejezowski-okta** [comment]
![Screen Shot 2020-07-10 at 3 46 10 PM](https://user-images.githubusercontent.com/49886075/87208766-948f0180-c2c4-11ea-8996-b9b09d3cfe6e.png)
![Screen Shot 2020-07-10 at 3 45 58 PM](https://user-images.githubusercontent.com/49886075/87208769-95279800-c2c4-11ea-95ee-68b5921951e1.png)

@edburyenegren-okta Thoughts?

**Comment by edburyenegren-okta** [comment]
Do we want the base grid size to optically match our line-height (24px for UI, 27.5px for display), the height of a UI text glyph (14px), or the height of display text glyph (16px)?

Since the implemented icon size won't match the grid size all the time, 16px feels like the most sane starting point - easily divisible, matches a normal rem, between sizes, so it won't have to scale too much up or down (e.g. shrinking for 14px)

I'm not sure if it's possible to attach SVGs directly to GH, but if you get me a handful, I can get some live examples up with the same CSS + different scale sizes.
