### ISSUE TITLE
Table (MVP)

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#67]
- [x] Inventory
- [x] Research
- [x] Explore
- [x] Create
- [x] Document
- [ ] Release

**Figma File:**
https://www.figma.com/file/ZKo95ME2djrr6XUakP7Yw9/Tables?node-id=0%3A1

**Reference JIRA Epic:**
https://oktainc.atlassian.net/browse/UX-1717?jql=component%20%3D%20%22Design%20System%22%20AND%20status%20!%3D%20Done

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta  @nickarcidy-okta @johnintrater-okta 

After our initial research I just wanted to pose some open questions so everyone can input here in the issue. Each question is numbered, so if you have opinions on something, answer what you'd like with the question number in front. 

1. Do we have an option that has borders, or no borders, both?
2. What additional features do we need to supply (sorting)
3. What content types do we support? (Numerical, dates, code)
4. What interactions do we support? (Hover, row clicking, links, buttons, dropdowns, header interactions)
5. Naming guidelines. How do we name our tables, headers (not eng or design related)
6. Do we allow multiple types of content per-cell? (example: Timestamp + Location)
7. Are interactions like search and filter considered as serarate components?
8. How do we decide when the table responds to small screen sizes. Large screens?
9. We use status’ a lot as it pertains to table rows. How should we handle this?
10. How do we handle iconography in tables?
11. What other UI’s should be allowed inside of a table?
12. What other UI’s should not be allowed inside of a table?

**Comment by edburyenegren-okta** [comment]
> 1. Do we have an option that has borders, or no borders, both?

I like our no-border version for now. Less based on aesthetics - more that it allows for tables to be placed inline with content or as a separate "space" on a page by adding a bordered container around it.

> 2. What additional features do we need to supply? (i.e. sorting)

I'd like to do sorting since it's pretty easy on our end; however, do we want to open the icon can of worms? (we could use the in-font glyphs for arrows right now?)

> 3. What content types do we support to start? (i.e. Numerical, dates, code)

The three you've listed feel solid to me for MVP. Might be a good item to do outreach about at our first feedback point.

> 4. What interactions do we support? (i.e. Hover, row clicking, links, buttons, dropdowns, header interactions)

Is this about what the table can do or what we allow in cells?

> 5. Naming guidelines. How do we name our tables, headers (not eng or design related)

Is this about `<caption>` and `<th>` naming? (trying to be specific)

> 6. Do we allow multiple types of content per-cell? (i.e. Timestamp + Location)

Please, no. But willing to budge.

> 7. Are interactions like search and filter considered as separate components?

Yeppers.

> 9. We use status’ a lot as it pertains to table rows. How should we handle this?

I have some ideas, but I'd be okay postponing this until we tackle Status.

> 11. What other UI’s should be allowed inside of a table?
> 12. What other UI’s should not be allowed inside of a table?

Been thinking about this a lot. Button, Tag, Link, Status, Icon all seem like likely/common use cases. Most inline UI might be "okay", and most block level UI is probably "absolutely not".

For interactive items like Button and Link, it should probably be limited to single-click UI (as opposed to something like an Input).

Another smell test for us might be, "would the table cell require extra styling to make this work?" Since these pieces of UI don't fall under "content type" styling specific to table, if they need additional styling to work, they are probably not a good candidate.

**Comment by FeliciaWang-okta** [comment]
+1 from ASA on prioritizing this

**Comment by johnintrater-okta** [comment]
+1 to @edburyenegren-okta comments above, especially around doing outreach at our first point of feedback for content types. Re border or no border, I gravitate to no border but that totally based on aesthetic only. What do you think @nickarcidy-okta?

**Comment by alexdahl-okta** [comment]
On `3` and `6`: dev docs will strongly want arbitrary and mixed cell content.

For example: https://developer.okta.com/docs/reference/api/users/#request-parameters

Perhaps some of our tables should be definition lists, but does seem like many should be tables.

**Comment by edburyenegren-okta** [comment]
@alexdahl-okta this example doesn't seem like a problem since the styled elements are all inline with the copy (and are treated exactly as copy)

the problematic use case would be when mixed content cells are introducing layout - like a title with subtitle under it in the same cell.

**Comment by joejezowski-okta** [comment]
Thanks @alexdahl-okta I see code snippets along with tags/chip UI's as some unique cases, are there any other content types you can think of?

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta 

**Re: #1** I think I'm on the no border train. I can see if designers really need or want it, they can either add it themselves and if the use case becomes strong enough, we can create a variant.

**Re: #5** I'm referring more about our variants like "default table" 

**Re: #6**  Agreed. Similar to the border/no border. Let designers bring up the use cases and we can weigh it out later.

**Comment by alexdahl-okta** [comment]
@joejezowski-okta, no other immediate content types for DevEx that I can think of... I bet more diverse things will come up over time, but I also bet that they won't be unique to DevEx. So, nothing to flag.

@edburyenegren-okta, cool, yeah by mixed content I was referring to paragraphs, links, chips, inline code, etc. But I guess they are all inline. The fanciest block formatting I imagine in a cell is a `<br>` or multiple `<p>`s, but even that doesn't seem like an immediate need.

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta Been playing around with some other libraries specifically their use of the checkbox component. I wanted your take on changing the row color if a user checks off a check box. I think its a nice addition.

**Comment by edburyenegren-okta** [comment]
@joejezowski-okta will you create a new ticket so we don't lose this idea?

**Comment by joejezowski-okta** [comment]
@edburyenegren-okta done!
