### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by joejezowski-okta** [okta/odyssey#89]
https://oktawiki.atlassian.net/wiki/spaces/UX/pages/626787270/Tabs

- [x] Audit current components
- [x] Audit product needs
- [x] Build Figma Component
- [x] Design Docs
- [x] Refactor existing CSS
- [x] Eng Doc update

**Comment by alexdahl-okta** [comment]
+1 from dev docs and OIN manager.

**Comment by joejezowski-okta** [comment]
@LanaChoi-okta can you throw up some examples in this thread or pass along any working files you have here?

**Comment by LanaChoi-okta** [comment]
![agents](https://user-images.githubusercontent.com/46703727/78187432-39c34f80-7423-11ea-8b0e-2ba573024fcc.png)
here is a mock of something coming out soon! so knowing how to deal with tabs would be nice. i've also seen a lot of tab use in first party apps, end user settings, etc. we may also need to consider all the levels of navigation... because some features require navigation within tabs (which is why i think we have the datalist pattern with tabs attached) so some guidelines around that will be helpful!

**Comment by joejezowski-okta** [comment]
Awesome! Thanks for sharing @LanaChoi-okta 

I think you hit the nail on the head with your assessment. We're noticing the same thing in our research. Can describe some issues, choices, or challenges you had designing with them?

Is there a scenario where you'd have more or less tabs here?

**Comment by jacobpuckett-okta** [comment]
These tabs are not getting developed currently, but are part of a POC for Account Settings which will be coming back up mid-year

cc @melissajones-okta 
![image](https://user-images.githubusercontent.com/48925519/78259598-ea385e80-74ca-11ea-90a2-aa4a7d3840a3.png)

**Comment by joejezowski-okta** [comment]
@jacobpuckett-okta Great, thank you!
