### ISSUE TITLE
Removed gray variations from latest update

### ISSUE THREAD

**Issue by dougchan-okta** [okta/odyssey#916]
- www.okta.com was built on Odyssey version `0.3.0` and relies heavily on `gray/300` and `gray/400` (but `0.3.0` didn't have `gray/500`). 
- We would like to update the Odyssey package in our repo so we can use `gray/500`, but the latest `_colors.scss` file removes `gray/300` and `gray/400`.

Any chance to re-add the `gray/300` and `gray/400` variations back to Odyssey?

**Comment by dougchan-okta** [comment]
Hey @edburyenegren-okta what do you think would be the best way for us to handle this moving forward so we can get the latest and greatest and update the npm package? We could always change `cv('gray', '300')` to `$odyssey-gray-300` and do a mass string replacement (or something like that) but wanted to get your thoughts first.

**Comment by edburyenegren-okta** [comment]
Hi @dougchan-okta, the upgrade path from that far back is tricky. For folks using the scss package, we highly recommend they use the tokens [here](https://github.com/okta/odyssey/blob/master/packages/odyssey/src/scss/abstracts/_tokens.scss) instead of referencing colors directly.

However, these tokens will also be refactored with the release of `1.0`. After that point, breaking changes should be much less likely.

**Comment by dougchan-okta** [comment]
Sounds good @edburyenegren-okta thanks for the response. We use a couple of the grays that we just noticed were deprecated (like gray/300) on our site in lots of places so we'll find a solution for that on our side. https://github.com/okta/odyssey/blob/master/packages/odyssey/src/scss/abstracts/_colors.scss

Just wanted to flag in case it was something your team wanted to be notified about. Thanks!
